"""Centralized Macedonian-language UI text for the whole app."""

APP_TITLE = "Потпишување и испраќање фактури"

# Tabs
TAB_RUN = "Потпишување и испраќање"
TAB_CUSTOMERS = "Клиенти"
TAB_SETTINGS = "Поставки"

# Customers tab
CUST_TABLE_ID = "ID на фирма"
CUST_TABLE_NAME = "Назив"
CUST_TABLE_EMAIL = "Е-пошта"
CUST_TABLE_UPDATED = "Последна промена"
CUST_ADD = "Додади клиент"
CUST_EDIT = "Измени"
CUST_DELETE = "Избриши"
CUST_IMPORT_CSV = "Увези од CSV"
CUST_SEARCH_PLACEHOLDER = "Пребарај по ID, назив или е-пошта..."
CUST_CONFIRM_DELETE_TITLE = "Потврда за бришење"
CUST_CONFIRM_DELETE_MSG = "Дали сте сигурни дека сакате да го избришете клиентот {id}?"

# CSV import dialog
IMPORT_TITLE = "Увоз на клиенти од CSV"
IMPORT_CHOOSE_FILE = "Избери CSV датотека"
IMPORT_COL_ID = "Колона за ID на фирма"
IMPORT_COL_NAME = "Колона за назив (опционално)"
IMPORT_COL_EMAIL = "Колона за е-пошта"
IMPORT_PREVIEW_TITLE = "Преглед пред увоз"
IMPORT_NEW = "Нови клиенти"
IMPORT_UNCHANGED = "Непроменети"
IMPORT_CONFLICTS = "Конфликти (различна е-пошта)"
IMPORT_CONFLICT_KEEP_EXISTING = "Задржи постоечка"
IMPORT_CONFLICT_USE_NEW = "Користи нова"
IMPORT_SUMMARY = "Нови: {new} • Непроменети: {unchanged} • Конфликти: {conflicts}"
IMPORT_APPLY = "Примени увоз"
IMPORT_CANCEL = "Откажи"
IMPORT_DONE = "Увозот е завршен. Додадени: {added}, ажурирани: {updated}."
IMPORT_ERROR_NO_COLUMNS = "Мора да изберете колона за ID и колона за е-пошта."
IMPORT_ERROR_READ = "Грешка при читање на CSV датотеката: {error}"

# Settings tab
SET_PATHS_GROUP = "Патеки"
SET_UNSIGNED_DIR = "Папка со непотпишани фактури"
SET_SIGNED_DIR = "Папка за потпишани фактури"
SET_BROWSE = "Избери..."
SET_FILENAME_GROUP = "Формат на име на датотека"
SET_FILENAME_SEPARATOR = "Разделувач"
SET_FILENAME_ID_INDEX = "Позиција на ID на фирма (по разделувач, почнувајќи од 1)"
SET_FILENAME_EXAMPLE = "Пример: {example} → ID на фирма = \"{extracted}\""
SET_SIGNING_MODE_GROUP = "Начин на потпишување"
SET_SIGNING_MODE_LABEL = "Тип"
SET_SIGNING_MODE_PKCS11 = "Реален USB токен (PKCS#11)"
SET_SIGNING_MODE_PKCS12 = "Тест сертификат (PKCS12) - само за пробување"
SET_SIGNING_MODE_WARNING = (
    "⚠ Тест сертификатот НЕ е важечки за вистински фактури. "
    "Користете го само за да се запознаете со апликацијата."
)
SET_PKCS12_PATH = "Датотека со тест сертификат (.p12)"
SET_PKCS12_PASSWORD = "Лозинка на сертификатот"

SET_TOKEN_GROUP = "USB токен за потпишување"
SET_TOKEN_DRIVER = "PKCS#11 драјвер (.dll)"
SET_TOKEN_SELECT = "Токен / сертификат"
SET_TOKEN_SCAN = "Скенирај токени"
SET_TOKEN_NONE_FOUND = "Не е пронајден токен. Проверете дали е приклучен и дали е избран точниот драјвер."
SET_TOKEN_SCAN_ERROR = "Грешка при скенирање токени: {error}"
SET_TOKEN_AUTO = "Автоматски (прв достапен)"
SET_EMAIL_GROUP = "Е-пошта за испраќање"
SET_EMAIL_ADDRESS = "Гмаил адреса"
SET_EMAIL_APP_PASSWORD = "Лозинка за апликација (App Password)"
SET_EMAIL_SUBJECT = "Наслов на порака"
SET_EMAIL_BODY = "Текст на порака"
SET_EMAIL_PLACEHOLDERS_HINT = "Може да користите: {invoice_id}, {customer_name}, {month}, {year}"
SET_SIGNATURE_APPEARANCE_GROUP = "Изглед на видливиот потпис (прва страница)"
SET_SIGNATURE_APPEARANCE_HINT = (
    "Повлечете го жолтото поле за да го поместите потписот, или повлечете го "
    "аголот долу-десно за да ја промените големината. Бројките се проценти "
    "од страницата."
)
SET_SIG_X = "Позиција X (%)"
SET_SIG_Y = "Позиција Y (%, од дното)"
SET_SIG_WIDTH = "Ширина (%)"
SET_SIG_HEIGHT = "Висина (%)"
SET_SIG_TEXT = "Текст на потписот"
SET_SIG_TEXT_HINT = "Може да користите: %(signer)s (име на потписникот), %(ts)s (датум/време). Притиснете Enter за нов ред."
SET_SIG_BACKGROUND = "Позадинска слика / watermark (по избор)"
SET_SIG_BACKGROUND_OPACITY = "Проѕирност на позадината"
SET_SIG_BACKGROUND_CLEAR = "Отстрани"

SET_SAVE = "Зачувај поставки"
SET_SAVED = "Поставките се зачувани."

# Run tab
RUN_SCAN = "Провери фактури"
RUN_SIGN = "Потпиши ги сите"
RUN_SEND = "Испрати ги сите потпишани"
RUN_OPEN_SIGNED_FOLDER = "Отвори папка со потпишани"
RUN_CANCEL = "Прекини"
RUN_PIN_TITLE = "PIN за USB токен"
RUN_PIN_LABEL = "Внесете PIN за токенот:"
RUN_PKCS12_PASSWORD_TITLE = "Лозинка за тест сертификат"
RUN_PKCS12_PASSWORD_LABEL = "Внесете ја лозинката на тест сертификатот:"
RUN_TABLE_FILE = "Датотека"
RUN_TABLE_CUSTOMER = "Клиент"
RUN_TABLE_EMAIL = "Е-пошта"
RUN_TABLE_STATUS = "Статус"
RUN_STATUS_PENDING = "Чека"
RUN_STATUS_NO_MATCH = "Нема пронајден клиент"
RUN_STATUS_SIGNING = "Се потпишува..."
RUN_STATUS_SIGNED = "Потпишано"
RUN_STATUS_SENDING = "Се испраќа..."
RUN_STATUS_SENT = "Испратено"
RUN_STATUS_SIGN_FAILED = "Неуспешно потпишување"
RUN_STATUS_SEND_FAILED = "Неуспешно испраќање"
RUN_STATUS_ALREADY_SIGNED = "Веќе потпишано"
RUN_STATUS_ALREADY_SENT = "Веќе испратено"
RUN_NO_FILES = "Нема пронајдени фактури во избраната папка."
RUN_SIGN_SUMMARY = "Потпишани: {ok} • Неуспешни: {failed} • Без клиент: {no_match}"
RUN_SEND_SUMMARY = "Испратени: {ok} • Неуспешни: {failed}"
RUN_EXPORT_REPORT = "Извези извештај (CSV)"
RUN_CONFIRM_TITLE = "Потврда"
RUN_CONFIRM_SIGN_MSG = "Ќе бидат потпишани {count} фактури. Продолжи?"
RUN_CONFIRM_SEND_MSG = "Ќе бидат испратени {count} потпишани фактури. Продолжи?"
RUN_ERROR_NO_DRIVER = "Прво изберете PKCS#11 драјвер во Поставки."
RUN_ERROR_NO_PKCS12 = "Прво изберете тест сертификат (.p12) во Поставки."
RUN_ERROR_NO_CREDS = "Прво внесете Гмаил адреса и App Password во Поставки."
RUN_ERROR_NO_PENDING = "Нема фактури подготвени за потпишување."
RUN_ERROR_NO_SIGNED = "Нема потпишани фактури подготвени за испраќање."
RUN_ERROR_BATCH = "Грешка при потпишување: {error}"
RUN_ERROR_FOLDER_MISSING = "Папката \"{path}\" не постои. Проверете ги поставките."

# Generic
BTN_OK = "Во ред"
BTN_CANCEL = "Откажи"
BTN_YES = "Да"
BTN_NO = "Не"
ERROR_TITLE = "Грешка"
