"""Centralized Macedonian-language UI text for the whole app."""

APP_TITLE = "Потпишување и испраќање фактури"

# Tabs
TAB_RUN = "Потпишување и испраќање"
TAB_CUSTOMERS = "Клиенти"
TAB_SETTINGS = "Поставки"

# Customers tab
CUST_TABLE_ID = "ID на фирма"
CUST_TABLE_NAME = "Назив"
CUST_TABLE_EMAIL = "Е-пошта"
CUST_TABLE_UPDATED = "Последна промена"
CUST_ADD = "Додади клиент"
CUST_EDIT = "Измени"
CUST_DELETE = "Избриши"
CUST_IMPORT_CSV = "Увези од CSV"
CUST_SEARCH_PLACEHOLDER = "Пребарај по ID, назив или е-пошта..."
CUST_CONFIRM_DELETE_TITLE = "Потврда за бришење"
CUST_CONFIRM_DELETE_MSG = "Дали сте сигурни дека сакате да го избришете клиентот {id}?"

# CSV import dialog
IMPORT_TITLE = "Увоз на клиенти од CSV"
IMPORT_CHOOSE_FILE = "Избери CSV датотека"
IMPORT_COL_ID = "Колона за ID на фирма"
IMPORT_COL_NAME = "Колона за назив (опционално)"
IMPORT_COL_EMAIL = "Колона за е-пошта"
IMPORT_PREVIEW_TITLE = "Преглед пред увоз"
IMPORT_NEW = "Нови клиенти"
IMPORT_UNCHANGED = "Непроменети"
IMPORT_CONFLICTS = "Конфликти (различна е-пошта)"
IMPORT_CONFLICT_KEEP_EXISTING = "Задржи постоечка"
IMPORT_CONFLICT_USE_NEW = "Користи нова"
IMPORT_SUMMARY = "Нови: {new} • Непроменети: {unchanged} • Конфликти: {conflicts}"
IMPORT_APPLY = "Примени увоз"
IMPORT_CANCEL = "Откажи"
IMPORT_DONE = "Увозот е завршен. Додадени: {added}, ажурирани: {updated}."
IMPORT_ERROR_NO_COLUMNS = "Мора да изберете колона за ID и колона за е-пошта."
IMPORT_ERROR_READ = "Грешка при читање на CSV датотеката: {error}"

# Settings tab
SET_PATHS_GROUP = "Патеки"
SET_UNSIGNED_DIR = "Папка со непотпишани фактури"
SET_SIGNED_DIR = "Папка за потпишани фактури"
SET_BROWSE = "Избери..."
SET_FILENAME_GROUP = "Формат на име на датотека"
SET_FILENAME_SEPARATOR = "Разделувач"
SET_FILENAME_ID_INDEX = "Позиција на ID на фирма (по разделувач, почнувајќи од 1)"
SET_FILENAME_EXAMPLE = "Пример: {example} → ID на фирма = \"{extracted}\""
SET_TOKEN_GROUP = "USB токен за потпишување"
SET_TOKEN_DRIVER = "PKCS#11 драјвер (.dll)"
SET_TOKEN_SLOT = "Слот (опционално, остави празно за автоматско)"
SET_TOKEN_TEST = "Тестирај токен"
SET_TOKEN_LIST_CERTS = "Прикажи сертификати"
SET_EMAIL_GROUP = "Е-пошта за испраќање"
SET_EMAIL_ADDRESS = "Гмаил адреса"
SET_EMAIL_APP_PASSWORD = "Лозинка за апликација (App Password)"
SET_EMAIL_SUBJECT = "Наслов на порака"
SET_EMAIL_BODY = "Текст на порака"
SET_EMAIL_PLACEHOLDERS_HINT = "Може да користите: {invoice_id}, {customer_name}, {month}, {year}"
SET_SAVE = "Зачувај поставки"
SET_SAVED = "Поставките се зачувани."

# Run tab
RUN_SCAN = "Провери фактури"
RUN_START = "Потпиши и испрати ги сите"
RUN_CANCEL = "Прекини"
RUN_PIN_TITLE = "PIN за USB токен"
RUN_PIN_LABEL = "Внесете PIN за токенот:"
RUN_TABLE_FILE = "Датотека"
RUN_TABLE_CUSTOMER = "Клиент"
RUN_TABLE_EMAIL = "Е-пошта"
RUN_TABLE_STATUS = "Статус"
RUN_STATUS_PENDING = "Чека"
RUN_STATUS_NO_MATCH = "Нема пронајден клиент"
RUN_STATUS_SIGNING = "Се потпишува..."
RUN_STATUS_SIGNED = "Потпишано"
RUN_STATUS_SENDING = "Се испраќа..."
RUN_STATUS_SENT = "Испратено"
RUN_STATUS_SIGN_FAILED = "Неуспешно потпишување"
RUN_STATUS_SEND_FAILED = "Неуспешно испраќање"
RUN_STATUS_ALREADY_SIGNED = "Веќе потпишано"
RUN_STATUS_ALREADY_SENT = "Веќе испратено"
RUN_NO_FILES = "Нема пронајдени фактури во избраната папка."
RUN_SUMMARY = "Потпишани и испратени: {ok} • Неуспешни: {failed} • Без клиент: {no_match}"
RUN_EXPORT_REPORT = "Извези извештај (CSV)"
RUN_CONFIRM_TITLE = "Потврда"
RUN_CONFIRM_MSG = "Ќе бидат потпишани и испратени {count} фактури. Продолжи?"
RUN_ERROR_NO_DRIVER = "Прво изберете PKCS#11 драјвер во Поставки."
RUN_ERROR_NO_CREDS = "Прво внесете Гмаил адреса и App Password во Поставки."
RUN_ERROR_NO_PENDING = "Нема фактури подготвени за потпишување и испраќање."
RUN_ERROR_BATCH = "Грешка при потпишување: {error}"
RUN_ERROR_FOLDER_MISSING = "Папката \"{path}\" не постои. Проверете ги поставките."

# Generic
BTN_OK = "Во ред"
BTN_CANCEL = "Откажи"
BTN_YES = "Да"
BTN_NO = "Не"
ERROR_TITLE = "Грешка"
